controller_joint_names: 
  - yumi_robl_joint_1
  - yumi_robl_joint_2
  - yumi_robl_joint_7
  - yumi_robl_joint_3
  - yumi_robl_joint_4
  - yumi_robl_joint_5
  - yumi_robl_joint_6
  # - gripper_l_joint
