# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 500



joint_vel_controller_1_l:
  type: "velocity_controllers/JointVelocityController"
  joint: yumi_robl_joint_1
joint_vel_controller_2_l:
  type: "velocity_controllers/JointVelocityController"
  joint: yumi_robl_joint_2
joint_vel_controller_7_l:
  type: "velocity_controllers/JointVelocityController"
  joint: yumi_robl_joint_7
joint_vel_controller_3_l:
  type: "velocity_controllers/JointVelocityController"
  joint: yumi_robl_joint_3
joint_vel_controller_4_l:
  type: "velocity_controllers/JointVelocityController"
  joint: yumi_robl_joint_4
joint_vel_controller_5_l:
  type: "velocity_controllers/JointVelocityController"
  joint: yumi_robl_joint_5
joint_vel_controller_6_l:
  type: "velocity_controllers/JointVelocityController"
  joint: yumi_robl_joint_6
joint_vel_controller_1_r:
  type: "velocity_controllers/JointVelocityController"
  joint: yumi_robr_joint_1
joint_vel_controller_2_r:
  type: "velocity_controllers/JointVelocityController"
  joint: yumi_robr_joint_2
joint_vel_controller_7_r:
  type: "velocity_controllers/JointVelocityController"
  joint: yumi_robr_joint_7
joint_vel_controller_3_r:
  type: "velocity_controllers/JointVelocityController"
  joint: yumi_robr_joint_3
joint_vel_controller_4_r:
  type: "velocity_controllers/JointVelocityController"
  joint: yumi_robr_joint_4
joint_vel_controller_5_r:
  type: "velocity_controllers/JointVelocityController"
  joint: yumi_robr_joint_5
joint_vel_controller_6_r:
  type: "velocity_controllers/JointVelocityController"
  joint: yumi_robr_joint_6




joint_group_vel_controller_l:
  type: "velocity_controllers/JointGroupVelocityController"
  joints:
    - yumi_robl_joint_1
    - yumi_robl_joint_2
    - yumi_robl_joint_7
    - yumi_robl_joint_3
    - yumi_robl_joint_4
    - yumi_robl_joint_5
    - yumi_robl_joint_6

joint_group_vel_controller_r:
  type: "velocity_controllers/JointGroupVelocityController"
  joints:
    - yumi_robr_joint_1
    - yumi_robr_joint_2
    - yumi_robr_joint_7
    - yumi_robr_joint_3
    - yumi_robr_joint_4
    - yumi_robr_joint_5
    - yumi_robr_joint_6

    
