controller_list:
  - name: fake_left_arm_controller
    joints:
      - yumi_robl_joint_1
      - yumi_robl_joint_2
      - yumi_robl_joint_7
      - yumi_robl_joint_3
      - yumi_robl_joint_4
      - yumi_robl_joint_5
      - yumi_robl_joint_6
  - name: fake_right_arm_controller
    joints:
      - yumi_robr_joint_1
      - yumi_robr_joint_2
      - yumi_robr_joint_7
      - yumi_robr_joint_3
      - yumi_robr_joint_4
      - yumi_robr_joint_5
      - yumi_robr_joint_6
  - name: fake_both_arms_controller
    joints:
      - yumi_robl_joint_1
      - yumi_robl_joint_2
      - yumi_robl_joint_7
      - yumi_robl_joint_3
      - yumi_robl_joint_4
      - yumi_robl_joint_5
      - yumi_robl_joint_6
      - yumi_robr_joint_1
      - yumi_robr_joint_2
      - yumi_robr_joint_7
      - yumi_robr_joint_3
      - yumi_robr_joint_4
      - yumi_robr_joint_5
      - yumi_robr_joint_6
  - name: fake_left_gripper_controller
    joints:
      - gripper_l_joint
  - name: fake_right_gripper_controller
    joints:
      - gripper_r_joint
